# Generated by Django 4.1.6 on 2023-02-12 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Heure_du_rdv',
            field=models.CharField(choices=[('9 AM', '9 AM'), ('9:30 AM', '9:30 AM'), ('10 AM', '10 AM'), ('10:30 AM', '10:30 AM'), ('11 AM', '11 AM'), ('11:30 AM', '11:30 AM'), ('12 PM', '12 PM'), ('12:30 PM', '12:30 PM'), ('1:30 PM', '1:30 PM'), ('2 PM', '2 PM'), ('2:30 PM', '2:30 PM'), ('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM')], default='3 PM', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Jour_du_rdv',
            field=models.DateField(choices=[('2023-02-13', '2023-02-13'), ('2023-02-14', '2023-02-14'), ('2023-02-15', '2023-02-15'), ('2023-02-16', '2023-02-16'), ('2023-02-17', '2023-02-17'), ('2023-02-20', '2023-02-20'), ('2023-02-21', '2023-02-21'), ('2023-02-22', '2023-02-22'), ('2023-02-23', '2023-02-23'), ('2023-02-24', '2023-02-24'), ('2023-02-27', '2023-02-27'), ('2023-02-28', '2023-02-28'), ('2023-03-01', '2023-03-01'), ('2023-03-02', '2023-03-02'), ('2023-03-03', '2023-03-03')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='Quel_est_l_objet_du_rdv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
