# Generated by Django 4.1.6 on 2023-02-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_appointment_day_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Jour_du_rdv',
            field=models.CharField(choices=[('2022-02-20', 'Lundi 20 Février'), ('2022-02-21', 'Mardi 21 Février'), ('2022-02-22', 'Mercredi 22 Février'), ('2022-02-23', 'Jeudi 23 Février'), ('2022-02-24', 'Vendredi 24 Février'), ('2022-02-27', 'Lundi 27 Février'), ('2022-02-28', 'Mardi 28 Février'), ('2022-03-01', 'Mercredi 1er Mars'), ('2022-03-02', 'Jeudi 2 Mars'), ('2022-03-03', 'Vendredi 3 Mars'), ('2022-03-06', 'Lundi 6 Mars'), ('2022-03-07', 'Mardi 7 Mars'), ('2022-03-08', 'Mercredi 8 Mars'), ('2022-03-09', 'Jeudi 9 Mars'), ('2022-03-10', 'Vendredi 10 Mars')], default='Lundi 20 Février', max_length=30),
        ),
    ]
