# Generated by Django 4.1.6 on 2023-02-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_jour_du_rdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Jour_du_rdv',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Heure_du_rdv',
            new_name='heure',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Quel_est_l_objet_du_rdv',
            new_name='objet',
        ),
    ]
