# Generated by Django 4.1.6 on 2023-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'heure')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
