# Generated by Django 4.1.6 on 2023-02-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_appointment_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='heure',
            new_name='horaire',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_available',
        ),
    ]
