# Generated by Django 4.1.6 on 2023-02-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_appointment_date_appointment_heure_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
