# Generated by Django 4.1.6 on 2023-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(choices=[('2023-02-14', 'mardi 14 février 2023'), ('2023-02-15', 'mercredi 15 février 2023'), ('2023-02-16', 'jeudi 16 février 2023'), ('2023-02-17', 'vendredi 17 février 2023'), ('2023-02-18', 'samedi 18 février 2023'), ('2023-02-19', 'dimanche 19 février 2023'), ('2023-02-20', 'lundi 20 février 2023'), ('2023-02-21', 'mardi 21 février 2023'), ('2023-02-22', 'mercredi 22 février 2023'), ('2023-02-23', 'jeudi 23 février 2023')], default='Lundi 20 Février', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='heure',
            field=models.CharField(choices=[('9 AM', '9 h'), ('9:30 AM', '9:30 AM'), ('10 AM', '10 AM'), ('10:30 AM', '10:30 AM'), ('11 AM', '11 AM'), ('11:30 AM', '11:30 AM'), ('12 PM', '12 PM'), ('12:30 PM', '12:30 PM'), ('1:30 PM', '1:30 PM'), ('2 PM', '2 PM'), ('2:30 PM', '2:30 PM'), ('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM')], default='3 PM', max_length=10),
        ),
    ]
