# Generated by Django 4.1.6 on 2023-02-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_appointment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Client',
        ),
    ]
