# Generated by Django 4.1.6 on 2023-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_appointment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='heure',
            field=models.CharField(choices=[('9 AM - 9:20 AM', '9h - 9h20'), ('9:30 AM - 9:50 AM', '9h30 - 9h50'), ('10 AM - 10:20 AM', '10h - 10h20'), ('10:30 AM - 10:50 AM', '10h30 - 10h50'), ('11 AM - 11:20 AM', '11h - 11h20'), ('11:30 AM - 11:50 AM', '11h30 - 11h50'), ('12 PM - 12:20 PM', '12h - 12h20'), ('12:30 PM - 12:50 PM', '12h30 - 12h50'), ('1:30 PM - 1:50 PM', '13h30 - 13h50'), ('2 PM - 2:20 PM', '14h - 14h20'), ('2:30 PM - 2:50 PM', '14h30 - 14h50'), ('3 PM - 3:20 PM', '15h - 15h20'), ('3:30 PM - 3:50 PM', '15h30 - 15h50'), ('4 PM - 4:20 PM', '16h - 16h20'), ('4:30 PM - 4:50 PM', '16h30 - 16h50')], default='3 PM', max_length=50),
        ),
    ]
