# Generated by Django 4.1.6 on 2023-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_appointment_client_alter_appointment_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(choices=[('2023-02-15', 'mercredi 15 février 2023'), ('2023-02-16', 'jeudi 16 février 2023'), ('2023-02-17', 'vendredi 17 février 2023'), ('2023-02-20', 'lundi 20 février 2023'), ('2023-02-21', 'mardi 21 février 2023'), ('2023-02-22', 'mercredi 22 février 2023'), ('2023-02-23', 'jeudi 23 février 2023'), ('2023-02-24', 'vendredi 24 février 2023')], default='Lundi 20 Février', max_length=30),
        ),
    ]
