# Generated by Django 4.1.6 on 2023-02-15 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(choices=[('2023-02-16', 'jeudi 16 février 2023'), ('2023-02-17', 'vendredi 17 février 2023'), ('2023-02-20', 'lundi 20 février 2023'), ('2023-02-21', 'mardi 21 février 2023'), ('2023-02-22', 'mercredi 22 février 2023'), ('2023-02-23', 'jeudi 23 février 2023'), ('2023-02-24', 'vendredi 24 février 2023'), ('2023-02-27', 'lundi 27 février 2023')], default='Lundi 20 Février', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='heure',
            field=models.CharField(choices=[('09:00 - 09:20', '9h - 9h20'), ('09:30 - 09:50', '9h30 - 9h50'), ('10:00 - 10:20', '10h - 10h20'), ('10:30 - 10:50', '10h30 - 10h50'), ('11:00 - 11:20', '11h - 11h20'), ('11:30 - 11:50', '11h30 - 11h50'), ('12:00 - 12:20', '12h - 12h20'), ('12:30 - 12:50', '12h30 - 12h50'), ('13:30 - 13:50', '13h30 - 13h50'), ('14:00 - 14:20', '14h - 14h20'), ('14:30 - 14:50', '14h30 - 14h50'), ('15:00 - 15:20', '15h - 15h20'), ('15:30 - 15:50', '15h30 - 15h50'), ('16:00 - 16:20', '16h - 16h20'), ('16:30 - 16:50', '16h30 - 16h50')], default='3 PM', max_length=50),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appointment')),
            ],
        ),
    ]
