# Generated by Django 4.1.6 on 2023-02-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
